### ISSUE TITLE
unable to make it dynamic validation by changing other elements as required and if we are removing required elements also above 3 fields showing error

### ISSUE THREAD

**Issue by tejashwiniChenna** [mauriciolauffer/openui5-validator#1]

**Comment by mauriciolauffer** [comment]
@tejashwiniChenna 
Could you give more details or even create an example at http://pluckr.nl ?
The example could be something like this https://embed.plnkr.co/220VmE

**Comment by mauriciolauffer** [comment]
@tejashwiniChenna 
This library is a wrapper for Ajv. You can check its documentation to see the limitations and how to deal with them.

https://github.com/epoberezkin/ajv
